https://github.com/canonical/cloud-init/commit/9a258eebd96aa5ad4486dba1fe86bea5bcf00c2f

=== Begin SRU Template ===
[Impact]
When using ENI, route '-net' parameter is incompatible with /32 IPv4 networks
without 'netmask' part so we have to use '-host' in that case.

[Test Case]
There is an upstream test for this bug:
https://github.com/canonical/cloud-init/blob/master/tests/integration_tests/bugs/test_gh668.py

=== Xenial ===
=================================================================================================================================== test session starts ====================================================================================================================================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, inifile: tox.ini
plugins: cov-2.9.0
collected 1 item

tests/integration_tests/bugs/test_gh668.py::test_static_route_to_host Detected image: image_id=xenial os=ubuntu release=xenial

-------------------------------------------------------------------------------------------------------------------------------------- live log setup --------------------------------------------------------------------------------------------------------------------------------------
2021-03-26 21:00:29 INFO      integration_testing:clouds.py:87 Detected image: image_id=xenial os=ubuntu release=xenial
Detected image: image_id=xenial os=ubuntu release=xenial
2021-03-26 21:00:29 INFO      integration_testing:clouds.py:87 Detected image: image_id=xenial os=ubuntu release=xenial
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=xenial
PLATFORM=lxd_container
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-03-26 21:00:39 INFO      integration_testing:clouds.py:128 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=xenial
PLATFORM=lxd_container
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for lxd_container
2021-03-26 21:00:39 INFO      integration_testing:conftest.py:156 Setting up environment for lxd_container
Launching instance with launch_kwargs:
user_data=None
image_id=ubuntu:fe7e6d31934ccd2ac010e18e7c324a2ca0c6ccc791c354fe4cc6af8449dbab21
2021-03-26 21:00:39 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
user_data=None
image_id=ubuntu:fe7e6d31934ccd2ac010e18e7c324a2ca0c6ccc791c354fe4cc6af8449dbab21
['lxc', 'init', 'ubuntu:fe7e6d31934ccd2ac010e18e7c324a2ca0c6ccc791c354fe4cc6af8449dbab21', '--config', 'user.meta-data=public-keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt\n']
2021-03-26 21:00:44 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:00:45 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 10.37.179.143
Retrying SSH connection to ubuntu@10.37.179.143:22 (598s left)
2021-03-26 21:00:46 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.2p2)
2021-03-26 21:00:46 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:00:46 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:00:47 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: LXDInstance(name=daring-kiwi)
2021-03-26 21:00:50 INFO      integration_testing:clouds.py:171 Launched instance: LXDInstance(name=daring-kiwi)
2021-03-26 21:00:50 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~16.04.1
2021-03-26 21:00:50 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~16.04.1
2021-03-26 21:00:50 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210316
2021-03-26 21:00:50 INFO      integration_testing:clouds.py:181 image serial: 20210316
Installing proposed image
2021-03-26 21:00:50 INFO      integration_testing:instances.py:144 Installing proposed image
2021-03-26 21:00:50 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2021-03-26 21:01:13 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~16.04.1
2021-03-26 21:01:13 INFO      integration_testing:instances.py:136 Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~16.04.1
2021-03-26 21:01:13 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-26 21:01:13 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-26 21:01:13 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-26 21:01:13 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-26 21:01:13 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-26 21:01:14 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
Created new image: local:daring-kiwi-snapshot
2021-03-26 21:01:48 INFO      integration_testing:instances.py:113 Created new image: local:daring-kiwi-snapshot
Done with environment setup
2021-03-26 21:01:49 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
user_data=None
execute_via_ssh=False
config_dict={'volatile.eth0.hwaddr': '02:00:00:31:71:82', 'user.network-config': 'version: 2\nethernets:\n  eth0:\n    addresses: [10.0.0.10/8]\n    dhcp4: false\n    routes:\n    - to: 172.16.0.10/32\n      via: 10.0.0.100\n    match:\n      macaddress: 02:00:00:31:71:82\n'}
image_id=local:daring-kiwi-snapshot
2021-03-26 21:01:49 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
user_data=None
execute_via_ssh=False
config_dict={'volatile.eth0.hwaddr': '02:00:00:31:71:82', 'user.network-config': 'version: 2\nethernets:\n  eth0:\n    addresses: [10.0.0.10/8]\n    dhcp4: false\n    routes:\n    - to: 172.16.0.10/32\n      via: 10.0.0.100\n    match:\n      macaddress: 02:00:00:31:71:82\n'}
image_id=local:daring-kiwi-snapshot
['lxc', 'init', 'local:daring-kiwi-snapshot', '--config', 'volatile.eth0.hwaddr=02:00:00:31:71:82', '--config', 'user.network-config=version: 2\nethernets:\n  eth0:\n    addresses: [10.0.0.10/8]\n    dhcp4: false\n    routes:\n    - to: 172.16.0.10/32\n      via: 10.0.0.100\n    match:\n      macaddress: 02:00:00:31:71:82\n', '--config', 'user.meta-data=public-keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt\n']
2021-03-26 21:01:58 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:01:58 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:01:58 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: LXDInstance(name=big-ox)
2021-03-26 21:02:01 INFO      integration_testing:clouds.py:171 Launched instance: LXDInstance(name=big-ox)
2021-03-26 21:02:01 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~16.04.1
2021-03-26 21:02:01 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~16.04.1
2021-03-26 21:02:01 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210316
2021-03-26 21:02:01 INFO      integration_testing:clouds.py:181 image serial: 20210316
-------------------------------------------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------------------------------------------
2021-03-26 21:02:01 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'ip route | grep 172.16.0.10'
PASSEDDeleting snapshot image created for this testrun: local:daring-kiwi-snapshot

------------------------------------------------------------------------------------------------------------------------------------ live log teardown -------------------------------------------------------------------------------------------------------------------------------------
2021-03-26 21:02:03 INFO      integration_testing:clouds.py:202 Deleting snapshot image created for this testrun: local:daring-kiwi-snapshot


=============================================================================================================================== 1 passed in 94.66s (0:01:34) ===============================================================================================================================


=== Bionic ===
n/a

=== Focal ===
n/a

=== Groovy ===
n/a

[Regression Potential]
This behavior will only affect Xenial. If somebody was relying on a
misconfigured network configuration, this will be a change in behavior.
