https://github.com/canonical/cloud-init/commit/4f62ae8d01e8caca9039af067280ca2adad6ab6d

=== Begin SRU Template ===
[Impact]
On Azure, with the changes for ssh public keys to be retrieved from IMDS as a first
option, when a key is passed through not in the raw ssh public key format it
causes an issue and the key is not added to the user's authorized_keys file.

[Test Case]
There is an upstream test for this bug:
https://github.com/canonical/cloud-init/blob/master/tests/integration_tests/bugs/test_lp1910835.py

=== Xenial ===
============================= test session starts ==============================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, inifile: tox.ini
plugins: cov-2.9.0
collected 1 item

tests/integration_tests/bugs/test_lp1910835.py::test_crlf_in_azure_metadata_ssh_keys Detected image: image_id=xenial os=ubuntu release=xenial

-------------------------------- live log setup --------------------------------
2021-03-26 21:05:56 INFO      integration_testing:clouds.py:87 Detected image: image_id=xenial os=ubuntu release=xenial
Detected image: image_id=xenial os=ubuntu release=xenial
2021-03-26 21:05:56 INFO      integration_testing:clouds.py:87 Detected image: image_id=xenial os=ubuntu release=xenial
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=xenial
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-03-26 21:05:56 INFO      integration_testing:clouds.py:128 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=xenial
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for azure
2021-03-26 21:05:56 INFO      integration_testing:conftest.py:156 Setting up environment for azure
Launching instance with launch_kwargs:
image_id=Canonical:UbuntuServer:16.04-DAILY-LTS
user_data=None
2021-03-26 21:05:56 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
image_id=Canonical:UbuntuServer:16.04-DAILY-LTS
user_data=None
2021-03-26 21:07:28 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:07:28 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.2p2)
2021-03-26 21:07:28 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:07:29 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:07:29 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f40bb0fc3c8>
2021-03-26 21:07:31 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f40bb0fc3c8>
2021-03-26 21:07:31 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~16.04.1
2021-03-26 21:07:32 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~16.04.1
2021-03-26 21:07:32 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210316
2021-03-26 21:07:32 INFO      integration_testing:clouds.py:181 image serial: 20210316
Installing proposed image
2021-03-26 21:07:32 INFO      integration_testing:instances.py:144 Installing proposed image
2021-03-26 21:07:32 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2021-03-26 21:07:50 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~16.04.1
2021-03-26 21:07:51 INFO      integration_testing:instances.py:136 Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~16.04.1
2021-03-26 21:07:51 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-26 21:07:51 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-26 21:07:51 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-26 21:07:52 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-26 21:07:52 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo waagent -deprovision+user -force'
Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-160556-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-160556-image
2021-03-26 21:09:01 INFO      integration_testing:instances.py:113 Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-160556-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-160556-image
Done with environment setup
2021-03-26 21:09:11 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-160556-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-160556-image
user_data=#cloud-config
ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt

vm_params={'os_profile': {'linux_configuration': {'ssh': {'public_keys': [{'key_data': 'ssh-rsa AAAAB3NzaC1y\r\nc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt\n', 'path': '/home/ubuntu/.ssh/authorized_keys'}]}}}}
-------------------------------- live log call ---------------------------------
2021-03-26 21:09:11 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-160556-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-160556-image
user_data=#cloud-config
ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt

vm_params={'os_profile': {'linux_configuration': {'ssh': {'public_keys': [{'key_data': 'ssh-rsa AAAAB3NzaC1y\r\nc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt\n', 'path': '/home/ubuntu/.ssh/authorized_keys'}]}}}}
2021-03-26 21:09:58 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:09:58 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.2p2)
2021-03-26 21:09:58 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:09:59 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:09:59 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f40bb0120b8>
2021-03-26 21:10:00 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f40bb0120b8>
2021-03-26 21:10:00 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~16.04.1
2021-03-26 21:10:00 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~16.04.1
2021-03-26 21:10:00 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210316
2021-03-26 21:10:01 INFO      integration_testing:clouds.py:181 image serial: 20210316
2021-03-26 21:10:01 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /home/ubuntu/.ssh/authorized_keys'
PASSEDDeleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-160556-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-160556-image

------------------------------ live log teardown -------------------------------
2021-03-26 21:10:41 INFO      integration_testing:clouds.py:202 Deleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-160556-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-160556-image


======================== 1 passed in 286.41s (0:04:46) =========================


=== Bionic ===
============================= test session starts ==============================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, inifile: tox.ini
plugins: cov-2.9.0
collected 1 item

tests/integration_tests/bugs/test_lp1910835.py::test_crlf_in_azure_metadata_ssh_keys Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------- live log setup --------------------------------
2021-03-26 21:18:35 INFO      integration_testing:clouds.py:87 Detected image: image_id=bionic os=ubuntu release=bionic
Detected image: image_id=bionic os=ubuntu release=bionic
2021-03-26 21:18:35 INFO      integration_testing:clouds.py:87 Detected image: image_id=bionic os=ubuntu release=bionic
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=bionic
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-03-26 21:18:35 INFO      integration_testing:clouds.py:128 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=bionic
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for azure
2021-03-26 21:18:35 INFO      integration_testing:conftest.py:156 Setting up environment for azure
Launching instance with launch_kwargs:
user_data=None
image_id=Canonical:UbuntuServer:18.04-DAILY-LTS
2021-03-26 21:18:35 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
user_data=None
image_id=Canonical:UbuntuServer:18.04-DAILY-LTS
2021-03-26 21:20:06 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:20:06 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 52.185.67.208
Retrying SSH connection to ubuntu@52.185.67.208:22 (599s left)
2021-03-26 21:20:07 INFO      pycloudlib.instance:instance.py:343 [Errno None] Unable to connect to port 22 on 52.185.67.208
Retrying SSH connection to ubuntu@52.185.67.208:22 (598s left)
2021-03-26 21:20:09 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-03-26 21:20:09 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:20:11 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:20:11 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f2b53298b38>
2021-03-26 21:20:12 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f2b53298b38>
2021-03-26 21:20:12 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~18.04.1
2021-03-26 21:20:13 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~18.04.1
2021-03-26 21:20:13 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210325
2021-03-26 21:20:13 INFO      integration_testing:clouds.py:181 image serial: 20210325
Installing proposed image
2021-03-26 21:20:13 INFO      integration_testing:instances.py:144 Installing proposed image
2021-03-26 21:20:13 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2021-03-26 21:20:33 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~18.04.1
2021-03-26 21:20:33 INFO      integration_testing:instances.py:136 Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~18.04.1
2021-03-26 21:20:33 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-26 21:20:34 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-26 21:20:34 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-26 21:20:34 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-26 21:20:35 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo waagent -deprovision+user -force'
Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-161835-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-161835-image
2021-03-26 21:21:58 INFO      integration_testing:instances.py:113 Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-161835-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-161835-image
Done with environment setup
2021-03-26 21:23:09 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
user_data=#cloud-config
ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt

image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-161835-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-161835-image
vm_params={'os_profile': {'linux_configuration': {'ssh': {'public_keys': [{'path': '/home/ubuntu/.ssh/authorized_keys', 'key_data': 'ssh-rsa AAAAB3NzaC1y\r\nc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt\n'}]}}}}
-------------------------------- live log call ---------------------------------
2021-03-26 21:23:09 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
user_data=#cloud-config
ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt

image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-161835-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-161835-image
vm_params={'os_profile': {'linux_configuration': {'ssh': {'public_keys': [{'path': '/home/ubuntu/.ssh/authorized_keys', 'key_data': 'ssh-rsa AAAAB3NzaC1y\r\nc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt\n'}]}}}}
2021-03-26 21:23:55 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:23:55 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-03-26 21:23:56 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:23:58 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:23:58 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f2b53bccb38>
2021-03-26 21:23:59 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f2b53bccb38>
2021-03-26 21:23:59 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~18.04.1
2021-03-26 21:24:00 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~18.04.1
2021-03-26 21:24:00 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210325
2021-03-26 21:24:00 INFO      integration_testing:clouds.py:181 image serial: 20210325
2021-03-26 21:24:00 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /home/ubuntu/.ssh/authorized_keys'
PASSEDDeleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-161835-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-161835-image

------------------------------ live log teardown -------------------------------
2021-03-26 21:24:40 INFO      integration_testing:clouds.py:202 Deleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-161835-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-161835-image


======================== 1 passed in 366.82s (0:06:06) =========================


=== Focal ===
============================= test session starts ==============================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, inifile: tox.ini
plugins: cov-2.9.0
collected 1 item

tests/integration_tests/bugs/test_lp1910835.py::test_crlf_in_azure_metadata_ssh_keys Detected image: image_id=focal os=ubuntu release=focal

-------------------------------- live log setup --------------------------------
2021-03-26 21:31:39 INFO      integration_testing:clouds.py:87 Detected image: image_id=focal os=ubuntu release=focal
Detected image: image_id=focal os=ubuntu release=focal
2021-03-26 21:31:40 INFO      integration_testing:clouds.py:87 Detected image: image_id=focal os=ubuntu release=focal
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=focal
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-03-26 21:31:40 INFO      integration_testing:clouds.py:128 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=focal
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for azure
2021-03-26 21:31:40 INFO      integration_testing:conftest.py:156 Setting up environment for azure
Launching instance with launch_kwargs:
image_id=Canonical:0001-com-ubuntu-server-focal-daily:20_04-daily-lts
user_data=None
2021-03-26 21:31:40 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
image_id=Canonical:0001-com-ubuntu-server-focal-daily:20_04-daily-lts
user_data=None
2021-03-26 21:33:11 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:33:11 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-03-26 21:33:12 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:33:13 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:33:13 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fb246c1ccc0>
2021-03-26 21:33:17 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fb246c1ccc0>
2021-03-26 21:33:17 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~20.04.1
2021-03-26 21:33:18 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~20.04.1
2021-03-26 21:33:18 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210325
2021-03-26 21:33:18 INFO      integration_testing:clouds.py:181 image serial: 20210325
Installing proposed image
2021-03-26 21:33:18 INFO      integration_testing:instances.py:144 Installing proposed image
2021-03-26 21:33:18 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2021-03-26 21:33:46 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~20.04.1
2021-03-26 21:33:47 INFO      integration_testing:instances.py:136 Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~20.04.1
2021-03-26 21:33:47 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-26 21:33:47 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-26 21:33:47 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-26 21:33:48 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-26 21:33:48 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo waagent -deprovision+user -force'
Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-163139-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-163140-image
2021-03-26 21:34:52 INFO      integration_testing:instances.py:113 Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-163139-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-163140-image
Done with environment setup
2021-03-26 21:35:32 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-163139-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-163140-image
user_data=#cloud-config
ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt

vm_params={'os_profile': {'linux_configuration': {'ssh': {'public_keys': [{'path': '/home/ubuntu/.ssh/authorized_keys', 'key_data': 'ssh-rsa AAAAB3NzaC1y\r\nc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt\n'}]}}}}
-------------------------------- live log call ---------------------------------
2021-03-26 21:35:32 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-163139-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-163140-image
user_data=#cloud-config
ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt

vm_params={'os_profile': {'linux_configuration': {'ssh': {'public_keys': [{'path': '/home/ubuntu/.ssh/authorized_keys', 'key_data': 'ssh-rsa AAAAB3NzaC1y\r\nc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt\n'}]}}}}
2021-03-26 21:36:19 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:36:19 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-03-26 21:36:19 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:36:21 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:36:22 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fb246cea080>
2021-03-26 21:36:22 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fb246cea080>
2021-03-26 21:36:22 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.04.1
2021-03-26 21:36:23 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.04.1
2021-03-26 21:36:23 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210325
2021-03-26 21:36:23 INFO      integration_testing:clouds.py:181 image serial: 20210325
2021-03-26 21:36:23 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /home/ubuntu/.ssh/authorized_keys'
PASSEDDeleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-163139-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-163140-image

------------------------------ live log teardown -------------------------------
2021-03-26 21:37:04 INFO      integration_testing:clouds.py:202 Deleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-163139-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-163140-image


======================== 1 passed in 325.48s (0:05:25) =========================


=== Groovy ===
============================= test session starts ==============================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, inifile: tox.ini
plugins: cov-2.9.0
collected 1 item

tests/integration_tests/bugs/test_lp1910835.py::test_crlf_in_azure_metadata_ssh_keys Detected image: image_id=groovy os=ubuntu release=groovy

-------------------------------- live log setup --------------------------------
2021-03-26 21:44:24 INFO      integration_testing:clouds.py:87 Detected image: image_id=groovy os=ubuntu release=groovy
Detected image: image_id=groovy os=ubuntu release=groovy
2021-03-26 21:44:25 INFO      integration_testing:clouds.py:87 Detected image: image_id=groovy os=ubuntu release=groovy
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=groovy
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-03-26 21:44:25 INFO      integration_testing:clouds.py:128 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
OS_IMAGE=groovy
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for azure
2021-03-26 21:44:25 INFO      integration_testing:conftest.py:156 Setting up environment for azure
Launching instance with launch_kwargs:
image_id=Canonical:0001-com-ubuntu-server-groovy-daily:20_10-daily
user_data=None
2021-03-26 21:44:25 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
image_id=Canonical:0001-com-ubuntu-server-groovy-daily:20_10-daily
user_data=None
2021-03-26 21:45:57 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:45:57 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.3p1)
2021-03-26 21:45:58 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:46:01 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:46:02 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fbf1cce3c88>
2021-03-26 21:46:05 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fbf1cce3c88>
2021-03-26 21:46:05 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~20.10.1
2021-03-26 21:46:06 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 20.4.1-0ubuntu1~20.10.1
2021-03-26 21:46:06 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210325
2021-03-26 21:46:06 INFO      integration_testing:clouds.py:181 image serial: 20210325
Installing proposed image
2021-03-26 21:46:06 INFO      integration_testing:instances.py:144 Installing proposed image
2021-03-26 21:46:06 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2021-03-26 21:46:34 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~20.10.1
2021-03-26 21:46:35 INFO      integration_testing:instances.py:136 Installed cloud-init version: 21.1-19-gbad84ad4-0ubuntu1~20.10.1
2021-03-26 21:46:35 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-26 21:46:35 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-26 21:46:35 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo cloud-init clean --logs'
2021-03-26 21:46:36 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-03-26 21:46:36 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'sudo waagent -deprovision+user -force'
Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-164424-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-164425-image
2021-03-26 21:47:40 INFO      integration_testing:instances.py:113 Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-164424-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-164425-image
Done with environment setup
2021-03-26 21:48:21 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-164424-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-164425-image
vm_params={'os_profile': {'linux_configuration': {'ssh': {'public_keys': [{'path': '/home/ubuntu/.ssh/authorized_keys', 'key_data': 'ssh-rsa AAAAB3NzaC1y\r\nc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt\n'}]}}}}
user_data=#cloud-config
ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt

-------------------------------- live log call ---------------------------------
2021-03-26 21:48:21 INFO      integration_testing:clouds.py:167 Launching instance with launch_kwargs:
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-164424-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-164425-image
vm_params={'os_profile': {'linux_configuration': {'ssh': {'public_keys': [{'path': '/home/ubuntu/.ssh/authorized_keys', 'key_data': 'ssh-rsa AAAAB3NzaC1y\r\nc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt\n'}]}}}}
user_data=#cloud-config
ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJMS8gdKw0kA1PDwAVkURrxgjbAgWVeiBq+VSOI1jFLafONDwkc0ZVriZofmCZ1BVjixCA6kqVQsmA88Av7eeI3jGvy4fwX+TKhDQk28rRC9mNz8nBLfB+gp3wfcgFJrVeekhjV+fgxiyq1wJC4WcJZfXKdXvsNTBzhd2RNZAsyKyRKBRahv57/KJjXozS94p83l0qq/gi6pYYBTTkLz65SiyVCUpkddgXDPfxEXqjsx6ha3VCdoKBdRgh3p2toADzcYafyqxDMPtfLJE+BofSA4Gi9YQAMhshdk4tzI+KYcq07cd8AtreXpVyZLC3r7cfe4m2IK7UvVSbTItYoUItN255P1M09eLQNlbbrJwnxuX3IUwxBkYZhVUIaEOQreWTnc+tg20ZK3olUzNWcJBurpeT5i6Hg/QoRrQSanVLFx8hff4l1V9Yxb23txlv9e2Pzh0i/0YVmrVlQxuen/5YyWNm553D1EfH8fEon3xVAqrbC8NS63GaP0QhGo7rlYs= james@newt

2021-03-26 21:49:07 INFO      pycloudlib.instance:instance.py:165 executing: sh -c whoami
2021-03-26 21:49:07 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.3p1)
2021-03-26 21:49:08 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-03-26 21:49:11 INFO      pycloudlib.instance:instance.py:165 executing: sh -c 'cloud-init status --help'
2021-03-26 21:49:12 INFO      pycloudlib.instance:instance.py:165 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fbf1d61c080>
2021-03-26 21:49:12 INFO      integration_testing:clouds.py:171 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fbf1d61c080>
2021-03-26 21:49:12 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.10.1
2021-03-26 21:49:13 INFO      integration_testing:clouds.py:177 cloud-init version: /usr/bin/cloud-init 21.1-19-gbad84ad4-0ubuntu1~20.10.1
2021-03-26 21:49:13 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210325
2021-03-26 21:49:13 INFO      integration_testing:clouds.py:181 image serial: 20210325
2021-03-26 21:49:13 INFO      pycloudlib.instance:instance.py:165 executing: sudo -- sh -c 'cat /home/ubuntu/.ssh/authorized_keys'
PASSEDDeleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-164424-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-164425-image

------------------------------ live log teardown -------------------------------
2021-03-26 21:49:54 INFO      integration_testing:clouds.py:202 Deleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0326-164424-rg/providers/Microsoft.Compute/images/azure-integration-test-0326-164425-image


======================== 1 passed in 330.10s (0:05:30) =========================


[Regression Potential]
This newly added broken functionality will continue to not work.
