============================= test session starts ==============================
platform linux -- Python 3.6.10, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/james/cloud-init, configfile: tox.ini
plugins: cov-2.10.1
collected 1 item

tests/integration_tests/modules/test_user_events.py::test_boot_event_enabled_by_default Detected image: image_id=hirsute os=ubuntu release=hirsute

-------------------------------- live log setup --------------------------------
2021-11-09 20:02:40 INFO      integration_testing:clouds.py:91 Detected image: image_id=hirsute os=ubuntu release=hirsute
Detected image: image_id=hirsute os=ubuntu release=hirsute
2021-11-09 20:02:40 INFO      integration_testing:clouds.py:91 Detected image: image_id=hirsute os=ubuntu release=hirsute
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=hirsute
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-11-09 20:02:40 INFO      integration_testing:clouds.py:132 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=hirsute
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for azure
2021-11-09 20:02:40 INFO      integration_testing:conftest.py:156 Setting up environment for azure
Launching instance with launch_kwargs:
image_id=Canonical:0001-com-ubuntu-server-hirsute-daily:21_04-daily
user_data=None
2021-11-09 20:02:40 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=Canonical:0001-com-ubuntu-server-hirsute-daily:21_04-daily
user_data=None
2021-11-09 20:04:14 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 20:04:14 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-11-09 20:04:14 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-09 20:04:16 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-09 20:04:16 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 20:04:16 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f32859660b8>
2021-11-09 20:04:17 INFO      integration_testing:clouds.py:176 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f32859660b8>
2021-11-09 20:04:17 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~21.04.4
2021-11-09 20:04:17 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~21.04.4
2021-11-09 20:04:17 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211109
2021-11-09 20:04:17 INFO      integration_testing:clouds.py:186 image serial: 20211109
Installing proposed image
2021-11-09 20:04:17 INFO      integration_testing:instances.py:152 Installing proposed image
2021-11-09 20:04:17 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-11-09 20:04:17 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
2021-11-09 20:04:27 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get install -qy cloud-init'
2021-11-09 20:04:40 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.4-0ubuntu1~21.04.1
2021-11-09 20:04:40 INFO      integration_testing:instances.py:139 Installed cloud-init version: 21.4-0ubuntu1~21.04.1
2021-11-09 20:04:40 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-11-09 20:04:41 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-11-09 20:04:41 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-11-09 20:04:41 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-11-09 20:04:42 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo waagent -deprovision+user -force'
Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-1109-140240-rg/providers/Microsoft.Compute/images/azure-integration-test-1109-140240-image
2021-11-09 20:05:45 INFO      integration_testing:instances.py:116 Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-1109-140240-rg/providers/Microsoft.Compute/images/azure-integration-test-1109-140240-image
Done with environment setup
2021-11-09 20:06:25 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-1109-140240-rg/providers/Microsoft.Compute/images/azure-integration-test-1109-140240-image
user_data=None
2021-11-09 20:06:25 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-1109-140240-rg/providers/Microsoft.Compute/images/azure-integration-test-1109-140240-image
user_data=None
2021-11-09 20:07:12 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 20:07:12 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-11-09 20:07:12 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-09 20:07:15 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-09 20:07:15 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 20:07:16 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f32850aa780>
2021-11-09 20:07:16 INFO      integration_testing:clouds.py:176 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7f32850aa780>
2021-11-09 20:07:16 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~21.04.1
2021-11-09 20:07:17 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~21.04.1
2021-11-09 20:07:17 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211109
2021-11-09 20:07:17 INFO      integration_testing:clouds.py:186 image serial: 20211109
-------------------------------- live log call ---------------------------------
2021-11-09 20:07:17 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-09 20:07:17 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ls /sys/class/net'
2021-11-09 20:07:17 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/netplan/50-cloud-init.yaml'
2021-11-09 20:07:17 INFO      paramiko.transport.sftp:sftp.py:158 [chan 9] Opened sftp connection (server version 3)
2021-11-09 20:07:17 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'mv /var/tmp/46b75576-0681-4586-918c-777e0d9fc8f2.tmp /etc/netplan/50-cloud-init.yaml'
2021-11-09 20:07:18 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo "" > /var/log/cloud-init.log'
Restarting instance and waiting for boot
2021-11-09 20:07:18 INFO      integration_testing:instances.py:68 Restarting instance and waiting for boot
2021-11-09 20:07:48 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 20:08:04 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-11-09 20:08:04 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-09 20:08:06 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-09 20:08:06 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 20:08:07 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 20:08:07 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
2021-11-09 20:08:07 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-09 20:08:07 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ls /sys/class/net'
PASSEDDeleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-1109-140240-rg/providers/Microsoft.Compute/images/azure-integration-test-1109-140240-image

------------------------------ live log teardown -------------------------------
2021-11-09 20:08:48 INFO      integration_testing:clouds.py:207 Deleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-1109-140240-rg/providers/Microsoft.Compute/images/azure-integration-test-1109-140240-image
------------------------------ live log logreport ------------------------------
2021-11-09 20:08:49 INFO      paramiko.transport.sftp:sftp.py:158 [chan 9] sftp session closed.


=============================== warnings summary ===============================
../envs/cloud-init36/lib/python3.6/site-packages/_pytest/config/__init__.py:1184
  /home/james/envs/cloud-init36/lib/python3.6/site-packages/_pytest/config/__init__.py:1184: PytestDeprecationWarning: The --strict option is deprecated, use --strict-markers instead.
    _pytest.deprecated.STRICT_OPTION, stacklevel=2

conftest.py:68
  /home/james/cloud-init/conftest.py:68: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(autouse=True)

conftest.py:168
  /home/james/cloud-init/conftest.py:168: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture

tests/integration_tests/conftest.py:104
  /home/james/cloud-init/tests/integration_tests/conftest.py:104: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='session')

tests/integration_tests/conftest.py:261
  /home/james/cloud-init/tests/integration_tests/conftest.py:261: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture

tests/integration_tests/conftest.py:268
  /home/james/cloud-init/tests/integration_tests/conftest.py:268: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='module')

tests/integration_tests/conftest.py:275
  /home/james/cloud-init/tests/integration_tests/conftest.py:275: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='class')

tests/integration_tests/modules/test_user_events.py: 44 warnings
  /home/james/envs/cloud-init36/lib/python3.6/site-packages/urllib3/util/retry.py:439: DeprecationWarning: Using 'method_whitelist' with Retry is deprecated and will be removed in v2.0. Use 'allowed_methods' instead
    DeprecationWarning,

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================== 1 passed, 51 warnings in 368.96s (0:06:08) ==================
