============================= test session starts ==============================
platform linux -- Python 3.6.10, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/james/cloud-init, configfile: tox.ini
plugins: cov-2.10.1
collected 1 item

tests/integration_tests/modules/test_ssh_auth_key_fingerprints.py::TestSshAuthkeyFingerprints::test_ssh_authkey_fingerprints_enable Detected image: image_id=hirsute os=ubuntu release=hirsute

-------------------------------- live log setup --------------------------------
2021-11-09 15:18:42 INFO      integration_testing:clouds.py:91 Detected image: image_id=hirsute os=ubuntu release=hirsute
Detected image: image_id=hirsute os=ubuntu release=hirsute
2021-11-09 15:18:57 INFO      integration_testing:clouds.py:91 Detected image: image_id=hirsute os=ubuntu release=hirsute
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=True
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=hirsute
PLATFORM=gce
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-11-09 15:19:03 INFO      integration_testing:clouds.py:132 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=True
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=hirsute
PLATFORM=gce
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for gce
2021-11-09 15:19:03 INFO      integration_testing:conftest.py:156 Setting up environment for gce
Launching instance with launch_kwargs:
image_id=projects/ubuntu-os-cloud-devel/global/images/daily-ubuntu-2104-hirsute-v20211104
user_data=None
2021-11-09 15:19:03 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=projects/ubuntu-os-cloud-devel/global/images/daily-ubuntu-2104-hirsute-v20211104
user_data=None
2021-11-09 15:19:16 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:19:32 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:19:33 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:19:34 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:19:35 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:19:36 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:19:37 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:19:39 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:19:40 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:19:41 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:19:42 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:19:43 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:19:43 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-11-09 15:19:44 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-09 15:20:31 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-09 15:20:32 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:20:33 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:20:34 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:20:34 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: GceInstance(instance_id=6256818023972679559)
2021-11-09 15:20:35 INFO      integration_testing:clouds.py:176 Launched instance: GceInstance(instance_id=6256818023972679559)
2021-11-09 15:20:35 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~21.04.4
2021-11-09 15:20:35 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~21.04.4
2021-11-09 15:20:35 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211104
2021-11-09 15:20:35 INFO      integration_testing:clouds.py:186 image serial: 20211104
Installing proposed image
2021-11-09 15:20:35 INFO      integration_testing:instances.py:152 Installing proposed image
2021-11-09 15:20:35 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-11-09 15:20:36 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
2021-11-09 15:20:46 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get install -qy cloud-init'
2021-11-09 15:20:53 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.4-0ubuntu1~21.04.1
2021-11-09 15:20:54 INFO      integration_testing:instances.py:139 Installed cloud-init version: 21.4-0ubuntu1~21.04.1
2021-11-09 15:20:54 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-11-09 15:20:54 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
Created new image: projects/ubuntu-server-277015/global/images/i0-gce-integration-test-1109-091842-image
2021-11-09 15:21:50 INFO      integration_testing:instances.py:116 Created new image: projects/ubuntu-server-277015/global/images/i0-gce-integration-test-1109-091842-image
Done with environment setup
2021-11-09 15:21:50 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
image_id=projects/ubuntu-server-277015/global/images/i0-gce-integration-test-1109-091842-image
user_data=#cloud-config
ssh_genkeytypes:
  - ecdsa
  - ed25519
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXW9Gg5H7ehjdSc6qDzwNtgCy94XYHhEYlXZMO2+FJrH3wfHGiMfCwOHxcOMt2QiXItULthdeQWS9QjBSSjVRXf6731igFrqPFyS9qBlOQ5D29C4HBXFnQggGVpBNJ82IRJv7szbbe/vpgLBP4kttUza9Dr4e1YM1ln4PRnjfXea6T0m+m1ixNb5432pTXlqYOnNOxSIm1gHgMLxPuDrJvQERDKrSiKSjIdyC9Jd8t2e1tkNLY0stmckVRbhShmcJvlyofHWbc2Ca1mmtP7MlS1VQnfLkvU1IrFwkmaQmaggX6WR6coRJ6XFXdWcq/AI2K6GjSnl1dnnCxE8VCEXBlXgFzad+PMSG4yiL5j8Oo1ZVpkTdgBnw4okGqTYCXyZg6X00As9IBNQfZMFlQXlIo4FiWgj3CO5QHQOyOX6FuEumaU13GnERrSSdp9tCs1Qm3/DG2RSCQBWTfcgMcStIvKqvJ3IjFn0vGLvI3Ampnq9q1SHwmmzAPSdzcMA76HyMUA5VWaBvWHlUxzIM6unxZASnwvuCzpywSEB5J2OF+p6H+cStJwQ32XwmOG8pLp1srlVWpqZI58Du/lzrkPqONphoZx0LDV86w7RUz1ksDzAdcm0tvmNRFMN1a0frDs506oA3aWK0oDk4Nmvk8sXGTYYw3iQSkOvDUUlIsqdaO+w==

2021-11-09 15:21:50 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=projects/ubuntu-server-277015/global/images/i0-gce-integration-test-1109-091842-image
user_data=#cloud-config
ssh_genkeytypes:
  - ecdsa
  - ed25519
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXW9Gg5H7ehjdSc6qDzwNtgCy94XYHhEYlXZMO2+FJrH3wfHGiMfCwOHxcOMt2QiXItULthdeQWS9QjBSSjVRXf6731igFrqPFyS9qBlOQ5D29C4HBXFnQggGVpBNJ82IRJv7szbbe/vpgLBP4kttUza9Dr4e1YM1ln4PRnjfXea6T0m+m1ixNb5432pTXlqYOnNOxSIm1gHgMLxPuDrJvQERDKrSiKSjIdyC9Jd8t2e1tkNLY0stmckVRbhShmcJvlyofHWbc2Ca1mmtP7MlS1VQnfLkvU1IrFwkmaQmaggX6WR6coRJ6XFXdWcq/AI2K6GjSnl1dnnCxE8VCEXBlXgFzad+PMSG4yiL5j8Oo1ZVpkTdgBnw4okGqTYCXyZg6X00As9IBNQfZMFlQXlIo4FiWgj3CO5QHQOyOX6FuEumaU13GnERrSSdp9tCs1Qm3/DG2RSCQBWTfcgMcStIvKqvJ3IjFn0vGLvI3Ampnq9q1SHwmmzAPSdzcMA76HyMUA5VWaBvWHlUxzIM6unxZASnwvuCzpywSEB5J2OF+p6H+cStJwQ32XwmOG8pLp1srlVWpqZI58Du/lzrkPqONphoZx0LDV86w7RUz1ksDzAdcm0tvmNRFMN1a0frDs506oA3aWK0oDk4Nmvk8sXGTYYw3iQSkOvDUUlIsqdaO+w==

2021-11-09 15:22:01 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:22:17 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:22:18 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:22:20 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:22:21 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:22:22 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:22:22 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-11-09 15:22:23 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-09 15:22:25 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-09 15:22:25 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:22:26 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:22:27 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:22:29 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:22:30 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:22:30 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: GceInstance(instance_id=7904087665893911776)
2021-11-09 15:22:30 INFO      integration_testing:clouds.py:176 Launched instance: GceInstance(instance_id=7904087665893911776)
2021-11-09 15:22:30 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~21.04.1
2021-11-09 15:22:31 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~21.04.1
2021-11-09 15:22:31 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211104
2021-11-09 15:22:31 INFO      integration_testing:clouds.py:186 image serial: 20211104
-------------------------------- live log call ---------------------------------
2021-11-09 15:22:31 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/syslog'
2021-11-09 15:22:33 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/syslog'
PASSEDDeleting snapshot image created for this testrun: projects/ubuntu-server-277015/global/images/i0-gce-integration-test-1109-091842-image

------------------------------ live log teardown -------------------------------
2021-11-09 15:22:33 INFO      integration_testing:clouds.py:207 Deleting snapshot image created for this testrun: projects/ubuntu-server-277015/global/images/i0-gce-integration-test-1109-091842-image


=============================== warnings summary ===============================
../envs/cloud-init36/lib/python3.6/site-packages/_pytest/config/__init__.py:1184
  /home/james/envs/cloud-init36/lib/python3.6/site-packages/_pytest/config/__init__.py:1184: PytestDeprecationWarning: The --strict option is deprecated, use --strict-markers instead.
    _pytest.deprecated.STRICT_OPTION, stacklevel=2

conftest.py:68
  /home/james/cloud-init/conftest.py:68: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(autouse=True)

conftest.py:168
  /home/james/cloud-init/conftest.py:168: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture

tests/integration_tests/conftest.py:104
  /home/james/cloud-init/tests/integration_tests/conftest.py:104: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='session')

tests/integration_tests/conftest.py:261
  /home/james/cloud-init/tests/integration_tests/conftest.py:261: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture

tests/integration_tests/conftest.py:268
  /home/james/cloud-init/tests/integration_tests/conftest.py:268: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='module')

tests/integration_tests/conftest.py:275
  /home/james/cloud-init/tests/integration_tests/conftest.py:275: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='class')

tests/integration_tests/modules/test_ssh_auth_key_fingerprints.py::TestSshAuthkeyFingerprints::test_ssh_authkey_fingerprints_enable
  /home/james/envs/cloud-init36/lib/python3.6/site-packages/simplestreams/mirrors/__init__.py:207: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    self.prefix, path)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================== 1 passed, 8 warnings in 232.06s (0:03:52) ===================
