============================= test session starts ==============================
platform linux -- Python 3.5.10, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/james/cloud-init, configfile: tox.ini
plugins: cov-2.12.1
collected 2 items

tests/integration_tests/test_upgrade.py::test_clean_boot_of_upgraded_package Detected image: image_id=focal os=ubuntu release=focal

-------------------------------- live log setup --------------------------------
2021-11-09 15:18:23 INFO      integration_testing:clouds.py:91 Detected image: image_id=focal os=ubuntu release=focal
Detected image: image_id=focal os=ubuntu release=focal
2021-11-09 15:18:25 INFO      integration_testing:clouds.py:91 Detected image: image_id=focal os=ubuntu release=focal
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=focal
PLATFORM=oci
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-11-09 15:18:26 INFO      integration_testing:clouds.py:132 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=focal
PLATFORM=oci
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Detected image: image_id=focal os=ubuntu release=focal
-------------------------------- live log call ---------------------------------
2021-11-09 15:18:26 INFO      integration_testing:clouds.py:91 Detected image: image_id=focal os=ubuntu release=focal
Launching instance with launch_kwargs:
image_id=ocid1.image.oc1.phx.aaaaaaaajkc5eazdu4xnnhc7oq4fi263zzyhqnfqqs37zzytg6sd5efuyv2q
user_data=#cloud-config
hostname: SRU-worked

2021-11-09 15:18:26 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=ocid1.image.oc1.phx.aaaaaaaajkc5eazdu4xnnhc7oq4fi263zzyhqnfqqs37zzytg6sd5efuyv2q
user_data=#cloud-config
hostname: SRU-worked

2021-11-09 15:19:02 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:19:19 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:19:20 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:19:20 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-11-09 15:19:21 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-09 15:19:24 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-09 15:19:24 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:19:25 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:19:26 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:19:28 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:19:29 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:19:30 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:19:31 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:19:31 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: OciInstance(instance_id=ocid1.instance.oc1.phx.anyhqljrniwq6syc3pgvvtxtkjoawnduo6y4wib6fv3svp3xrryzzm4kt6oq, compartment_id=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa)
2021-11-09 15:19:32 INFO      integration_testing:clouds.py:176 Launched instance: OciInstance(instance_id=ocid1.instance.oc1.phx.anyhqljrniwq6syc3pgvvtxtkjoawnduo6y4wib6fv3svp3xrryzzm4kt6oq, compartment_id=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa)
2021-11-09 15:19:32 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~20.04.4
2021-11-09 15:19:33 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~20.04.4
2021-11-09 15:19:33 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211015
2021-11-09 15:19:33 INFO      integration_testing:clouds.py:186 image serial: 20211015
2021-11-09 15:19:33 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c hostname
2021-11-09 15:19:33 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c cloud-id
2021-11-09 15:19:34 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /run/cloud-init/result.json'
2021-11-09 15:19:34 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/netplan/50-cloud-init.yaml'
2021-11-09 15:19:35 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c systemd-analyze
2021-11-09 15:19:35 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'systemd-analyze blame'
2021-11-09 15:19:36 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init analyze show'
2021-11-09 15:19:37 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init analyze blame'
2021-11-09 15:19:38 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
Installing proposed image
2021-11-09 15:19:39 INFO      integration_testing:instances.py:152 Installing proposed image
2021-11-09 15:19:39 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-11-09 15:19:39 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
Installing proposed image
2021-11-09 15:19:42 INFO      integration_testing:instances.py:152 Installing proposed image
2021-11-09 15:19:42 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-11-09 15:19:42 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
Installing proposed image
2021-11-09 15:19:45 INFO      integration_testing:instances.py:152 Installing proposed image
2021-11-09 15:19:45 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-11-09 15:19:46 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
Installing proposed image
2021-11-09 15:19:49 INFO      integration_testing:instances.py:152 Installing proposed image
2021-11-09 15:19:49 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-11-09 15:19:49 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
2021-11-09 15:20:02 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get install -qy cloud-init'
2021-11-09 15:20:10 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.4-0ubuntu1~20.04.1
2021-11-09 15:20:11 INFO      integration_testing:instances.py:139 Installed cloud-init version: 21.4-0ubuntu1~20.04.1
2021-11-09 15:20:11 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-11-09 15:20:12 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-11-09 15:20:12 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init init'
2021-11-09 15:20:13 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'hostname something-else'
Restarting instance and waiting for boot
2021-11-09 15:20:14 INFO      integration_testing:instances.py:68 Restarting instance and waiting for boot
2021-11-09 15:20:14 INFO      pycloudlib.instance:instance.py:175 executing: sh -c sync
2021-11-09 15:20:21 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:20:39 ERROR     paramiko.transport:transport.py:1819 Socket exception: Connection reset by peer (104)
2021-11-09 15:20:40 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:20:40 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-11-09 15:20:40 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-09 15:20:42 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-09 15:20:42 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:20:44 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:20:45 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:20:46 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:20:47 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:20:48 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:20:49 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:20:51 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:20:51 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
2021-11-09 15:20:52 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init status --wait --long'
2021-11-09 15:20:53 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c hostname
2021-11-09 15:20:53 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c cloud-id
2021-11-09 15:20:54 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /run/cloud-init/result.json'
2021-11-09 15:20:54 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/netplan/50-cloud-init.yaml'
2021-11-09 15:20:54 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c systemd-analyze
2021-11-09 15:20:54 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'systemd-analyze blame'
2021-11-09 15:20:56 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init analyze show'
2021-11-09 15:20:57 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init analyze blame'
2021-11-09 15:20:58 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'

=== `systemd-analyze` before:
Startup finished in 5.020s (kernel) + 20.171s (userspace) = 25.191s
graphical.target reached after 17.357s in userspace
=== `systemd-analyze` after:
Startup finished in 5.041s (kernel) + 18.594s (userspace) = 23.636s
graphical.target reached after 15.429s in userspace

=== `systemd-analyze blame` before (first 10 lines):
7.129s snapd.seeded.service
2.659s cloud-init.service
2.584s snapd.apparmor.service
2.250s cloud-init-local.service
1.675s snapd.service
1.504s cloud-config.service
1.312s cloud-final.service
1.128s pollinate.service
1.114s dev-sda1.device
 980ms apparmor.service
=== `systemd-analyze blame` after (first 10 lines):
9.630s snap.lxd.activate.service
9.446s snapd.service
1.712s cloud-config.service
1.449s cloud-final.service
1.421s cloud-init-local.service
1.401s cloud-init.service
1.154s dev-sda1.device
1.008s networkd-dispatcher.service
 889ms accounts-daemon.service
 882ms systemd-udev-settle.service

=== `cloud-init analyze show` before:')
Finished stage: (init-local) 00.77400 seconds
Finished stage: (init-network) 01.85900 seconds
Finished stage: (modules-config) 00.62700 seconds
Finished stage: (modules-final) 00.44500 seconds
Total Time: 3.70500 seconds
=== `cloud-init analyze show` after:')
Finished stage: (init-network) 00.70100 seconds
Finished stage: (init-local) 00.38400 seconds
Total Time: 1.08500 seconds
Finished stage: (init-network) 00.80700 seconds
Finished stage: (modules-config) 00.70800 seconds
Finished stage: (modules-final) 00.28000 seconds
Total Time: 1.79500 seconds

=== `cloud-init analyze blame` before (first 10 lines): ')
-- Boot Record 01 --
     00.57100s (init-network/config-ssh)
     00.51200s (init-network/config-growpart)
     00.44200s (init-network/config-resizefs)
     00.38200s (modules-config/config-grub-dpkg)
     00.27900s (modules-final/config-ssh-authkey-fingerprints)
     00.17000s (init-local/search-Oracle)
     00.14500s (modules-config/config-apt-configure)
     00.12800s (init-network/config-users-groups)
     00.06100s (modules-final/config-keys-to-console)
=== `cloud-init analyze blame` after (first 10 lines): ')
-- Boot Record 01 --
     00.38600s (init-network/config-ssh)
     00.08900s (init-local/search-Oracle)
     00.05400s (init-network/config-growpart)
     00.03500s (init-network/config-users-groups)
     00.02900s (init-network/config-write-files)
     00.02400s (init-network/config-resizefs)
     00.01100s (init-network/config-set_hostname)
     00.00800s (init-local/check-cache)
     00.00400s (init-network/consume-user-data)

2021-11-09 15:20:58 INFO      integration_testing.test_upgrade:test_upgrade.py:151
=== `systemd-analyze` before:
Startup finished in 5.020s (kernel) + 20.171s (userspace) = 25.191s
graphical.target reached after 17.357s in userspace
=== `systemd-analyze` after:
Startup finished in 5.041s (kernel) + 18.594s (userspace) = 23.636s
graphical.target reached after 15.429s in userspace

=== `systemd-analyze blame` before (first 10 lines):
7.129s snapd.seeded.service
2.659s cloud-init.service
2.584s snapd.apparmor.service
2.250s cloud-init-local.service
1.675s snapd.service
1.504s cloud-config.service
1.312s cloud-final.service
1.128s pollinate.service
1.114s dev-sda1.device
 980ms apparmor.service
=== `systemd-analyze blame` after (first 10 lines):
9.630s snap.lxd.activate.service
9.446s snapd.service
1.712s cloud-config.service
1.449s cloud-final.service
1.421s cloud-init-local.service
1.401s cloud-init.service
1.154s dev-sda1.device
1.008s networkd-dispatcher.service
 889ms accounts-daemon.service
 882ms systemd-udev-settle.service

=== `cloud-init analyze show` before:')
Finished stage: (init-local) 00.77400 seconds
Finished stage: (init-network) 01.85900 seconds
Finished stage: (modules-config) 00.62700 seconds
Finished stage: (modules-final) 00.44500 seconds
Total Time: 3.70500 seconds
=== `cloud-init analyze show` after:')
Finished stage: (init-network) 00.70100 seconds
Finished stage: (init-local) 00.38400 seconds
Total Time: 1.08500 seconds
Finished stage: (init-network) 00.80700 seconds
Finished stage: (modules-config) 00.70800 seconds
Finished stage: (modules-final) 00.28000 seconds
Total Time: 1.79500 seconds

=== `cloud-init analyze blame` before (first 10 lines): ')
-- Boot Record 01 --
     00.57100s (init-network/config-ssh)
     00.51200s (init-network/config-growpart)
     00.44200s (init-network/config-resizefs)
     00.38200s (modules-config/config-grub-dpkg)
     00.27900s (modules-final/config-ssh-authkey-fingerprints)
     00.17000s (init-local/search-Oracle)
     00.14500s (modules-config/config-apt-configure)
     00.12800s (init-network/config-users-groups)
     00.06100s (modules-final/config-keys-to-console)
=== `cloud-init analyze blame` after (first 10 lines): ')
-- Boot Record 01 --
     00.38600s (init-network/config-ssh)
     00.08900s (init-local/search-Oracle)
     00.05400s (init-network/config-growpart)
     00.03500s (init-network/config-users-groups)
     00.02900s (init-network/config-write-files)
     00.02400s (init-network/config-resizefs)
     00.01100s (init-network/config-set_hostname)
     00.00800s (init-local/check-cache)
     00.00400s (init-network/consume-user-data)

PASSED
tests/integration_tests/modules/test_set_hostname.py::TestHostname::test_hostname Detected image: image_id=focal os=ubuntu release=focal

-------------------------------- live log setup --------------------------------
2021-11-09 15:22:11 INFO      integration_testing:clouds.py:91 Detected image: image_id=focal os=ubuntu release=focal
Setting up environment for oci
2021-11-09 15:22:11 INFO      integration_testing:conftest.py:156 Setting up environment for oci
Launching instance with launch_kwargs:
image_id=ocid1.image.oc1.phx.aaaaaaaajkc5eazdu4xnnhc7oq4fi263zzyhqnfqqs37zzytg6sd5efuyv2q
user_data=None
2021-11-09 15:22:11 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=ocid1.image.oc1.phx.aaaaaaaajkc5eazdu4xnnhc7oq4fi263zzyhqnfqqs37zzytg6sd5efuyv2q
user_data=None
2021-11-09 15:22:48 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:23:05 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-11-09 15:23:06 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-09 15:23:09 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-09 15:23:09 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:23:10 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:23:11 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:23:12 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:23:14 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:23:15 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:23:15 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: OciInstance(instance_id=ocid1.instance.oc1.phx.anyhqljrniwq6sycuck3zjudqpynykiqztkwlzxzljnoqy34pv365zcne7ia, compartment_id=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa)
2021-11-09 15:23:16 INFO      integration_testing:clouds.py:176 Launched instance: OciInstance(instance_id=ocid1.instance.oc1.phx.anyhqljrniwq6sycuck3zjudqpynykiqztkwlzxzljnoqy34pv365zcne7ia, compartment_id=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa)
2021-11-09 15:23:16 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~20.04.4
2021-11-09 15:23:17 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~20.04.4
2021-11-09 15:23:17 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211015
2021-11-09 15:23:17 INFO      integration_testing:clouds.py:186 image serial: 20211015
Installing proposed image
2021-11-09 15:23:17 INFO      integration_testing:instances.py:152 Installing proposed image
2021-11-09 15:23:17 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-11-09 15:23:17 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
Installing proposed image
2021-11-09 15:23:19 INFO      integration_testing:instances.py:152 Installing proposed image
2021-11-09 15:23:19 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-11-09 15:23:19 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
Installing proposed image
2021-11-09 15:23:21 INFO      integration_testing:instances.py:152 Installing proposed image
2021-11-09 15:23:21 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-11-09 15:23:21 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
Installing proposed image
2021-11-09 15:23:23 INFO      integration_testing:instances.py:152 Installing proposed image
2021-11-09 15:23:23 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-11-09 15:23:23 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
Installing proposed image
2021-11-09 15:23:27 INFO      integration_testing:instances.py:152 Installing proposed image
2021-11-09 15:23:27 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-11-09 15:23:27 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
Installing proposed image
2021-11-09 15:23:32 INFO      integration_testing:instances.py:152 Installing proposed image
2021-11-09 15:23:32 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-11-09 15:23:32 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
2021-11-09 15:23:43 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get install -qy cloud-init'
2021-11-09 15:23:51 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.4-0ubuntu1~20.04.1
2021-11-09 15:23:52 INFO      integration_testing:instances.py:139 Installed cloud-init version: 21.4-0ubuntu1~20.04.1
2021-11-09 15:23:52 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-11-09 15:23:52 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-11-09 15:23:53 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-11-09 15:23:53 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
Created new image: ocid1.image.oc1.phx.aaaaaaaaeq73ox2gft43basqvqq6hjbey6nkrc7f5nbwkzcld3hms5qj6x3q
2021-11-09 15:26:03 INFO      integration_testing:instances.py:116 Created new image: ocid1.image.oc1.phx.aaaaaaaaeq73ox2gft43basqvqq6hjbey6nkrc7f5nbwkzcld3hms5qj6x3q
Done with environment setup
2021-11-09 15:27:13 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
image_id=ocid1.image.oc1.phx.aaaaaaaaeq73ox2gft43basqvqq6hjbey6nkrc7f5nbwkzcld3hms5qj6x3q
user_data=#cloud-config
hostname: cloudinit2

2021-11-09 15:27:13 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=ocid1.image.oc1.phx.aaaaaaaaeq73ox2gft43basqvqq6hjbey6nkrc7f5nbwkzcld3hms5qj6x3q
user_data=#cloud-config
hostname: cloudinit2

2021-11-09 15:27:48 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-09 15:28:04 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-11-09 15:28:05 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-09 15:28:06 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-09 15:28:07 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:28:08 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:28:09 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:28:10 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:28:11 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:28:12 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:28:14 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:28:15 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:28:16 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:28:17 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-09 15:28:17 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: OciInstance(instance_id=ocid1.instance.oc1.phx.anyhqljrniwq6sycl5mh2rjox2eibbz7cgvlx7m6ttmcoacpi7syphgdfsjq, compartment_id=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa)
2021-11-09 15:28:18 INFO      integration_testing:clouds.py:176 Launched instance: OciInstance(instance_id=ocid1.instance.oc1.phx.anyhqljrniwq6sycl5mh2rjox2eibbz7cgvlx7m6ttmcoacpi7syphgdfsjq, compartment_id=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa)
2021-11-09 15:28:18 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~20.04.1
2021-11-09 15:28:19 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~20.04.1
2021-11-09 15:28:19 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211015
2021-11-09 15:28:19 INFO      integration_testing:clouds.py:186 image serial: 20211015
-------------------------------- live log call ---------------------------------
2021-11-09 15:28:19 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c hostname
PASSEDDeleting snapshot image created for this testrun: ocid1.image.oc1.phx.aaaaaaaaeq73ox2gft43basqvqq6hjbey6nkrc7f5nbwkzcld3hms5qj6x3q

------------------------------ live log teardown -------------------------------
2021-11-09 15:29:27 INFO      integration_testing:clouds.py:207 Deleting snapshot image created for this testrun: ocid1.image.oc1.phx.aaaaaaaaeq73ox2gft43basqvqq6hjbey6nkrc7f5nbwkzcld3hms5qj6x3q


=============================== warnings summary ===============================
../envs/cloud-init/lib/python3.5/site-packages/jwt/utils.py:8
  /home/james/envs/cloud-init/lib/python3.5/site-packages/jwt/utils.py:8: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
    from cryptography.hazmat.primitives.asymmetric.utils import (

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=================== 2 passed, 1 warning in 665.10s (0:11:05) ===================
