============================= test session starts ==============================
platform linux -- Python 3.6.10, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, configfile: tox.ini
plugins: cov-2.10.1
collected 2 items

tests/integration_tests/modules/test_hotplug.py::test_hotplug_add_remove Detected image: image_id=30dab618-32e1-4756-ac41-c72cc46b1eba os=ubuntu release=hirsute

-------------------------------- live log setup --------------------------------
2021-11-12 15:28:42 INFO      integration_testing:clouds.py:91 Detected image: image_id=30dab618-32e1-4756-ac41-c72cc46b1eba os=ubuntu release=hirsute
Detected image: image_id=30dab618-32e1-4756-ac41-c72cc46b1eba os=ubuntu release=hirsute
2021-11-12 15:28:42 INFO      integration_testing:clouds.py:91 Detected image: image_id=30dab618-32e1-4756-ac41-c72cc46b1eba os=ubuntu release=hirsute
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/home/james/tmp_home/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=30dab618-32e1-4756-ac41-c72cc46b1eba::ubuntu::hirsute
PLATFORM=openstack
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-11-12 15:28:42 INFO      integration_testing:clouds.py:132 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/home/james/tmp_home/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=30dab618-32e1-4756-ac41-c72cc46b1eba::ubuntu::hirsute
PLATFORM=openstack
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for openstack
2021-11-12 15:28:42 INFO      integration_testing:conftest.py:156 Setting up environment for openstack
Launching instance with launch_kwargs:
image_id=30dab618-32e1-4756-ac41-c72cc46b1eba
user_data=None
2021-11-12 15:28:42 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=30dab618-32e1-4756-ac41-c72cc46b1eba
user_data=None
2021-11-12 15:29:30 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:29:34 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:29:39 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:29:40 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:29:41 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:29:42 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:29:43 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:29:44 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:29:45 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:29:47 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:29:48 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:29:50 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:29:51 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:29:52 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:29:52 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-11-12 15:29:52 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-12 15:29:57 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-12 15:29:57 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:29:58 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:29:59 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:30:00 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:30:00 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: OpenstackInstance(instance_id=eb320932-8add-433b-9d40-e5a8bb5f1e43)
2021-11-12 15:30:01 INFO      integration_testing:clouds.py:176 Launched instance: OpenstackInstance(instance_id=eb320932-8add-433b-9d40-e5a8bb5f1e43)
2021-11-12 15:30:01 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~21.04.4
2021-11-12 15:30:02 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~21.04.4
2021-11-12 15:30:02 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211025
2021-11-12 15:30:02 INFO      integration_testing:clouds.py:186 image serial: 20211025
Installing proposed image
2021-11-12 15:30:02 INFO      integration_testing:instances.py:152 Installing proposed image
2021-11-12 15:30:02 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-11-12 15:30:02 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
2021-11-12 15:30:15 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get install -qy cloud-init'
2021-11-12 15:30:24 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.4-0ubuntu1~21.04.1
2021-11-12 15:30:24 INFO      integration_testing:instances.py:139 Installed cloud-init version: 21.4-0ubuntu1~21.04.1
2021-11-12 15:30:24 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-11-12 15:30:25 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-11-12 15:30:25 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-11-12 15:30:25 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
Created new image: 77697c36-a9ba-4be1-9519-c3c51b9f99b9
2021-11-12 15:32:04 INFO      integration_testing:instances.py:116 Created new image: 77697c36-a9ba-4be1-9519-c3c51b9f99b9
Done with environment setup
2021-11-12 15:32:08 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
image_id=77697c36-a9ba-4be1-9519-c3c51b9f99b9
user_data=#cloud-config
updates:
  network:
    when: ['hotplug']

2021-11-12 15:32:08 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=77697c36-a9ba-4be1-9519-c3c51b9f99b9
user_data=#cloud-config
updates:
  network:
    when: ['hotplug']

2021-11-12 15:33:10 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:33:15 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:33:19 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:33:20 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:33:21 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:33:22 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:33:23 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:33:24 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:33:26 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:33:27 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:33:27 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-11-12 15:33:28 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-12 15:33:29 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-12 15:33:29 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:33:31 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:33:32 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:33:33 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:33:34 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:33:35 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:33:35 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: OpenstackInstance(instance_id=a38bb768-7394-47b9-add4-fa05f905f651)
2021-11-12 15:33:36 INFO      integration_testing:clouds.py:176 Launched instance: OpenstackInstance(instance_id=a38bb768-7394-47b9-add4-fa05f905f651)
2021-11-12 15:33:36 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~21.04.1
2021-11-12 15:33:36 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~21.04.1
2021-11-12 15:33:36 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211025
2021-11-12 15:33:36 INFO      integration_testing:clouds.py:186 image serial: 20211025
-------------------------------- live log call ---------------------------------
2021-11-12 15:33:36 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ip --brief addr'
2021-11-12 15:33:37 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:33:37 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'test -f /etc/udev/rules.d/10-cloud-init-hook-hotplug.rules'
2021-11-12 15:33:46 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:33:47 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:33:48 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:33:49 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:33:51 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:33:52 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:33:53 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:33:53 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ip --brief addr'
2021-11-12 15:33:54 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/netplan/50-cloud-init.yaml'
2021-11-12 15:33:55 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:33:57 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:33:58 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:33:59 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:34:00 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:34:02 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:34:03 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:34:04 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:34:05 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:34:07 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:34:08 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:34:09 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:34:10 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:34:11 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ip --brief addr'
2021-11-12 15:34:11 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/netplan/50-cloud-init.yaml'
2021-11-12 15:34:11 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init devel hotplug-hook -s net query'
PASSED
tests/integration_tests/modules/test_hotplug.py::test_no_hotplug_in_userdata Detected image: image_id=30dab618-32e1-4756-ac41-c72cc46b1eba os=ubuntu release=hirsute

-------------------------------- live log setup --------------------------------
2021-11-12 15:34:20 INFO      integration_testing:clouds.py:91 Detected image: image_id=30dab618-32e1-4756-ac41-c72cc46b1eba os=ubuntu release=hirsute
Launching instance with launch_kwargs:
image_id=77697c36-a9ba-4be1-9519-c3c51b9f99b9
user_data=None
2021-11-12 15:34:20 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=77697c36-a9ba-4be1-9519-c3c51b9f99b9
user_data=None
2021-11-12 15:34:32 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:34:36 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:34:40 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:34:41 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:34:43 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:34:44 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:34:45 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:34:46 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:34:48 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:34:49 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:34:49 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-11-12 15:34:49 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-12 15:34:53 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-12 15:34:53 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:34:54 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:34:55 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:34:56 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:34:57 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: OpenstackInstance(instance_id=03a2bb94-75c4-4c90-8654-28a4770b1a79)
2021-11-12 15:34:57 INFO      integration_testing:clouds.py:176 Launched instance: OpenstackInstance(instance_id=03a2bb94-75c4-4c90-8654-28a4770b1a79)
2021-11-12 15:34:57 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~21.04.1
2021-11-12 15:34:58 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~21.04.1
2021-11-12 15:34:58 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211025
2021-11-12 15:34:58 INFO      integration_testing:clouds.py:186 image serial: 20211025
-------------------------------- live log call ---------------------------------
2021-11-12 15:34:58 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ip --brief addr'
2021-11-12 15:34:58 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:34:58 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'test -f /etc/udev/rules.d/10-cloud-init-hook-hotplug.rules'
2021-11-12 15:35:11 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:35:11 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ip --brief addr'
2021-11-12 15:35:12 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init devel hotplug-hook -s net query'
PASSEDDeleting snapshot image created for this testrun: 77697c36-a9ba-4be1-9519-c3c51b9f99b9

------------------------------ live log teardown -------------------------------
2021-11-12 15:35:19 INFO      integration_testing:clouds.py:207 Deleting snapshot image created for this testrun: 77697c36-a9ba-4be1-9519-c3c51b9f99b9


=============================== warnings summary ===============================
../envs/cloud-init36/lib/python3.6/site-packages/_pytest/config/__init__.py:1184
  /home/james/envs/cloud-init36/lib/python3.6/site-packages/_pytest/config/__init__.py:1184: PytestDeprecationWarning: The --strict option is deprecated, use --strict-markers instead.
    _pytest.deprecated.STRICT_OPTION, stacklevel=2

conftest.py:68
  /home/james/cloud-init-tests/conftest.py:68: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(autouse=True)

conftest.py:168
  /home/james/cloud-init-tests/conftest.py:168: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture

tests/integration_tests/conftest.py:104
  /home/james/cloud-init-tests/tests/integration_tests/conftest.py:104: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='session')

tests/integration_tests/conftest.py:270
  /home/james/cloud-init-tests/tests/integration_tests/conftest.py:270: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture

tests/integration_tests/conftest.py:277
  /home/james/cloud-init-tests/tests/integration_tests/conftest.py:277: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='module')

tests/integration_tests/conftest.py:284
  /home/james/cloud-init-tests/tests/integration_tests/conftest.py:284: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='class')

tests/integration_tests/modules/test_hotplug.py: 519 warnings
  /home/james/envs/cloud-init36/lib/python3.6/site-packages/openstack/resource.py:351: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
    len(inspect.getargspec(type_).args) > 1)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================= 2 passed, 526 warnings in 403.55s (0:06:43) ==================
