============================= test session starts ==============================
platform linux -- Python 3.6.10, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, configfile: tox.ini
plugins: cov-2.10.1
collected 2 items

tests/integration_tests/modules/test_hotplug.py::test_hotplug_add_remove Detected image: image_id=f2c501e3-aa16-4625-908b-2a809a72aa0c os=ubuntu release=focal

-------------------------------- live log setup --------------------------------
2021-11-12 15:20:22 INFO      integration_testing:clouds.py:91 Detected image: image_id=f2c501e3-aa16-4625-908b-2a809a72aa0c os=ubuntu release=focal
Detected image: image_id=f2c501e3-aa16-4625-908b-2a809a72aa0c os=ubuntu release=focal
2021-11-12 15:20:22 INFO      integration_testing:clouds.py:91 Detected image: image_id=f2c501e3-aa16-4625-908b-2a809a72aa0c os=ubuntu release=focal
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/home/james/tmp_home/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=f2c501e3-aa16-4625-908b-2a809a72aa0c::ubuntu::focal
PLATFORM=openstack
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-11-12 15:20:22 INFO      integration_testing:clouds.py:132 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/home/james/tmp_home/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=f2c501e3-aa16-4625-908b-2a809a72aa0c::ubuntu::focal
PLATFORM=openstack
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for openstack
2021-11-12 15:20:22 INFO      integration_testing:conftest.py:156 Setting up environment for openstack
Launching instance with launch_kwargs:
image_id=f2c501e3-aa16-4625-908b-2a809a72aa0c
user_data=None
2021-11-12 15:20:22 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=f2c501e3-aa16-4625-908b-2a809a72aa0c
user_data=None
2021-11-12 15:20:43 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:20:47 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:20:51 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:20:53 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:20:55 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:20:56 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:20:57 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:20:58 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:20:59 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:21:01 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:21:02 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:21:03 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:21:04 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:21:05 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:21:05 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-11-12 15:21:06 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-12 15:21:08 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-12 15:21:08 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:21:10 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:21:11 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:21:12 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:21:13 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:21:14 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:21:15 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:21:16 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:21:17 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:21:19 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:21:20 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:21:20 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: OpenstackInstance(instance_id=1fefb848-893f-4349-912f-918f873f564d)
2021-11-12 15:21:20 INFO      integration_testing:clouds.py:176 Launched instance: OpenstackInstance(instance_id=1fefb848-893f-4349-912f-918f873f564d)
2021-11-12 15:21:20 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~20.04.4
2021-11-12 15:21:21 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~20.04.4
2021-11-12 15:21:21 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211021
2021-11-12 15:21:21 INFO      integration_testing:clouds.py:186 image serial: 20211021
Installing proposed image
2021-11-12 15:21:21 INFO      integration_testing:instances.py:152 Installing proposed image
2021-11-12 15:21:21 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-11-12 15:21:21 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
2021-11-12 15:21:38 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get install -qy cloud-init'
2021-11-12 15:21:49 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.4-0ubuntu1~20.04.1
2021-11-12 15:21:50 INFO      integration_testing:instances.py:139 Installed cloud-init version: 21.4-0ubuntu1~20.04.1
2021-11-12 15:21:50 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-11-12 15:21:50 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-11-12 15:21:51 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-11-12 15:21:51 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
Created new image: 27d0997c-e9bd-41ca-a000-d9069b6c8ced
2021-11-12 15:23:58 INFO      integration_testing:instances.py:116 Created new image: 27d0997c-e9bd-41ca-a000-d9069b6c8ced
Done with environment setup
2021-11-12 15:24:04 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
image_id=27d0997c-e9bd-41ca-a000-d9069b6c8ced
user_data=#cloud-config
updates:
  network:
    when: ['hotplug']

2021-11-12 15:24:04 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=27d0997c-e9bd-41ca-a000-d9069b6c8ced
user_data=#cloud-config
updates:
  network:
    when: ['hotplug']

2021-11-12 15:25:04 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:25:08 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:25:12 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:25:14 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:25:15 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:25:16 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:25:17 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:25:19 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:25:20 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:25:24 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:25:25 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:25:26 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:25:26 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-11-12 15:25:26 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-12 15:25:28 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-12 15:25:28 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:25:29 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:25:30 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:25:31 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:25:32 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:25:32 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: OpenstackInstance(instance_id=6368a898-fd57-4217-810d-044ce1da0b7b)
2021-11-12 15:25:33 INFO      integration_testing:clouds.py:176 Launched instance: OpenstackInstance(instance_id=6368a898-fd57-4217-810d-044ce1da0b7b)
2021-11-12 15:25:33 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~20.04.1
2021-11-12 15:25:34 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~20.04.1
2021-11-12 15:25:34 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211021
2021-11-12 15:25:34 INFO      integration_testing:clouds.py:186 image serial: 20211021
-------------------------------- live log call ---------------------------------
2021-11-12 15:25:34 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ip --brief addr'
2021-11-12 15:25:34 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:25:34 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'test -f /etc/udev/rules.d/10-cloud-init-hook-hotplug.rules'
2021-11-12 15:25:46 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:25:47 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:25:48 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:25:49 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:25:51 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:25:52 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:25:53 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:25:54 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ip --brief addr'
2021-11-12 15:25:54 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/netplan/50-cloud-init.yaml'
2021-11-12 15:25:55 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:25:56 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:25:58 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:25:59 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:26:00 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:26:01 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:26:02 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:26:04 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:26:05 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:26:06 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:26:07 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:26:09 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:26:10 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:26:11 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:26:11 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ip --brief addr'
2021-11-12 15:26:12 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/netplan/50-cloud-init.yaml'
2021-11-12 15:26:12 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init devel hotplug-hook -s net query'
PASSED
tests/integration_tests/modules/test_hotplug.py::test_no_hotplug_in_userdata Detected image: image_id=f2c501e3-aa16-4625-908b-2a809a72aa0c os=ubuntu release=focal

-------------------------------- live log setup --------------------------------
2021-11-12 15:26:17 INFO      integration_testing:clouds.py:91 Detected image: image_id=f2c501e3-aa16-4625-908b-2a809a72aa0c os=ubuntu release=focal
Launching instance with launch_kwargs:
image_id=27d0997c-e9bd-41ca-a000-d9069b6c8ced
user_data=None
2021-11-12 15:26:17 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=27d0997c-e9bd-41ca-a000-d9069b6c8ced
user_data=None
2021-11-12 15:27:37 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:27:41 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:27:45 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:27:46 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:27:47 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:27:48 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:27:50 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:27:52 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:27:54 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:27:55 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:27:56 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:27:57 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:27:57 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.2p1)
2021-11-12 15:27:57 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-12 15:27:59 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-12 15:27:59 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:28:00 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:28:01 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:28:02 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:28:03 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:28:03 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: OpenstackInstance(instance_id=0328df99-8aae-46c4-9c5b-eaba820076b9)
2021-11-12 15:28:04 INFO      integration_testing:clouds.py:176 Launched instance: OpenstackInstance(instance_id=0328df99-8aae-46c4-9c5b-eaba820076b9)
2021-11-12 15:28:04 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~20.04.1
2021-11-12 15:28:05 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~20.04.1
2021-11-12 15:28:05 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211021
2021-11-12 15:28:05 INFO      integration_testing:clouds.py:186 image serial: 20211021
-------------------------------- live log call ---------------------------------
2021-11-12 15:28:05 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ip --brief addr'
2021-11-12 15:28:05 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:28:05 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'test -f /etc/udev/rules.d/10-cloud-init-hook-hotplug.rules'
2021-11-12 15:28:22 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:28:23 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ip --brief addr'
2021-11-12 15:28:23 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init devel hotplug-hook -s net query'
PASSEDDeleting snapshot image created for this testrun: 27d0997c-e9bd-41ca-a000-d9069b6c8ced

------------------------------ live log teardown -------------------------------
2021-11-12 15:28:35 INFO      integration_testing:clouds.py:207 Deleting snapshot image created for this testrun: 27d0997c-e9bd-41ca-a000-d9069b6c8ced


=============================== warnings summary ===============================
../envs/cloud-init36/lib/python3.6/site-packages/_pytest/config/__init__.py:1184
  /home/james/envs/cloud-init36/lib/python3.6/site-packages/_pytest/config/__init__.py:1184: PytestDeprecationWarning: The --strict option is deprecated, use --strict-markers instead.
    _pytest.deprecated.STRICT_OPTION, stacklevel=2

conftest.py:68
  /home/james/cloud-init-tests/conftest.py:68: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(autouse=True)

conftest.py:168
  /home/james/cloud-init-tests/conftest.py:168: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture

tests/integration_tests/conftest.py:104
  /home/james/cloud-init-tests/tests/integration_tests/conftest.py:104: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='session')

tests/integration_tests/conftest.py:270
  /home/james/cloud-init-tests/tests/integration_tests/conftest.py:270: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture

tests/integration_tests/conftest.py:277
  /home/james/cloud-init-tests/tests/integration_tests/conftest.py:277: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='module')

tests/integration_tests/conftest.py:284
  /home/james/cloud-init-tests/tests/integration_tests/conftest.py:284: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='class')

tests/integration_tests/modules/test_hotplug.py: 672 warnings
  /home/james/envs/cloud-init36/lib/python3.6/site-packages/openstack/resource.py:351: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
    len(inspect.getargspec(type_).args) > 1)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================= 2 passed, 679 warnings in 498.77s (0:08:18) ==================
