============================= test session starts ==============================
platform linux -- Python 3.6.10, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, configfile: tox.ini
plugins: cov-2.10.1
collected 2 items

tests/integration_tests/modules/test_hotplug.py::test_hotplug_add_remove Detected image: image_id=827195be-5e47-40f1-8f40-32c30b4965b7 os=ubuntu release=impish

-------------------------------- live log setup --------------------------------
2021-11-12 15:35:28 INFO      integration_testing:clouds.py:91 Detected image: image_id=827195be-5e47-40f1-8f40-32c30b4965b7 os=ubuntu release=impish
Detected image: image_id=827195be-5e47-40f1-8f40-32c30b4965b7 os=ubuntu release=impish
2021-11-12 15:35:28 INFO      integration_testing:clouds.py:91 Detected image: image_id=827195be-5e47-40f1-8f40-32c30b4965b7 os=ubuntu release=impish
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/home/james/tmp_home/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=827195be-5e47-40f1-8f40-32c30b4965b7::ubuntu::impish
PLATFORM=openstack
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-11-12 15:35:28 INFO      integration_testing:clouds.py:132 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/home/james/tmp_home/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=827195be-5e47-40f1-8f40-32c30b4965b7::ubuntu::impish
PLATFORM=openstack
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for openstack
2021-11-12 15:35:28 INFO      integration_testing:conftest.py:156 Setting up environment for openstack
Launching instance with launch_kwargs:
image_id=827195be-5e47-40f1-8f40-32c30b4965b7
user_data=None
2021-11-12 15:35:28 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=827195be-5e47-40f1-8f40-32c30b4965b7
user_data=None
2021-11-12 15:36:09 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:36:13 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:36:18 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:36:19 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:36:20 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:36:21 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:36:22 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:36:23 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:36:25 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:36:27 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:36:28 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:36:29 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:36:30 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:36:30 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-11-12 15:36:30 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-12 15:36:33 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-12 15:36:34 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:36:35 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:36:36 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:36:37 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:36:37 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: OpenstackInstance(instance_id=68fe868c-159d-44f1-962c-9180024e4d64)
2021-11-12 15:36:38 INFO      integration_testing:clouds.py:176 Launched instance: OpenstackInstance(instance_id=68fe868c-159d-44f1-962c-9180024e4d64)
2021-11-12 15:36:38 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu3
2021-11-12 15:36:38 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu3
2021-11-12 15:36:38 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211014
2021-11-12 15:36:38 INFO      integration_testing:clouds.py:186 image serial: 20211014
Installing proposed image
2021-11-12 15:36:38 INFO      integration_testing:instances.py:152 Installing proposed image
2021-11-12 15:36:38 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-11-12 15:36:39 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
2021-11-12 15:36:51 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get install -qy cloud-init'
2021-11-12 15:37:00 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.4-0ubuntu1~21.10.1
2021-11-12 15:37:01 INFO      integration_testing:instances.py:139 Installed cloud-init version: 21.4-0ubuntu1~21.10.1
2021-11-12 15:37:01 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-11-12 15:37:02 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-11-12 15:37:02 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-11-12 15:37:02 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
Created new image: 1da51f15-d80a-4493-ae9b-8eb612b94391
2021-11-12 15:38:19 INFO      integration_testing:instances.py:116 Created new image: 1da51f15-d80a-4493-ae9b-8eb612b94391
Done with environment setup
2021-11-12 15:38:24 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
image_id=1da51f15-d80a-4493-ae9b-8eb612b94391
user_data=#cloud-config
updates:
  network:
    when: ['hotplug']

2021-11-12 15:38:24 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=1da51f15-d80a-4493-ae9b-8eb612b94391
user_data=#cloud-config
updates:
  network:
    when: ['hotplug']

2021-11-12 15:39:11 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:39:15 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:39:18 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:39:19 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:39:20 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:39:21 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:39:23 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:39:24 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:39:26 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:39:27 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:39:27 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-11-12 15:39:27 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-12 15:39:28 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-12 15:39:28 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:39:29 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:39:30 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: OpenstackInstance(instance_id=27a43d24-22ed-42ef-9915-2148ac68f487)
2021-11-12 15:39:30 INFO      integration_testing:clouds.py:176 Launched instance: OpenstackInstance(instance_id=27a43d24-22ed-42ef-9915-2148ac68f487)
2021-11-12 15:39:30 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~21.10.1
2021-11-12 15:39:31 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~21.10.1
2021-11-12 15:39:31 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211014
2021-11-12 15:39:31 INFO      integration_testing:clouds.py:186 image serial: 20211014
-------------------------------- live log call ---------------------------------
2021-11-12 15:39:31 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ip --brief addr'
2021-11-12 15:39:31 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:39:31 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'test -f /etc/udev/rules.d/10-cloud-init-hook-hotplug.rules'
2021-11-12 15:39:40 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:39:41 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:39:42 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:39:43 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:39:44 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:39:46 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:39:47 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:39:47 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ip --brief addr'
2021-11-12 15:39:48 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/netplan/50-cloud-init.yaml'
2021-11-12 15:39:49 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:39:50 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:39:52 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:39:53 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:39:54 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:39:55 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:39:57 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:39:58 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:39:59 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:40:00 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:40:01 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:40:03 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:40:04 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:40:04 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ip --brief addr'
2021-11-12 15:40:05 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/netplan/50-cloud-init.yaml'
2021-11-12 15:40:05 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init devel hotplug-hook -s net query'
PASSED
tests/integration_tests/modules/test_hotplug.py::test_no_hotplug_in_userdata Detected image: image_id=827195be-5e47-40f1-8f40-32c30b4965b7 os=ubuntu release=impish

-------------------------------- live log setup --------------------------------
2021-11-12 15:40:11 INFO      integration_testing:clouds.py:91 Detected image: image_id=827195be-5e47-40f1-8f40-32c30b4965b7 os=ubuntu release=impish
Launching instance with launch_kwargs:
image_id=1da51f15-d80a-4493-ae9b-8eb612b94391
user_data=None
2021-11-12 15:40:11 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=1da51f15-d80a-4493-ae9b-8eb612b94391
user_data=None
2021-11-12 15:41:01 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:41:05 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:41:09 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:41:10 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:41:11 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:41:12 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:41:13 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:41:14 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:41:15 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:41:17 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:41:18 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-12 15:41:19 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.4p1)
2021-11-12 15:41:19 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-12 15:41:21 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-12 15:41:21 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:41:22 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-12 15:41:22 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: OpenstackInstance(instance_id=c4639152-6ea1-42f3-8c1c-5caa655cc7fb)
2021-11-12 15:41:23 INFO      integration_testing:clouds.py:176 Launched instance: OpenstackInstance(instance_id=c4639152-6ea1-42f3-8c1c-5caa655cc7fb)
2021-11-12 15:41:23 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~21.10.1
2021-11-12 15:41:23 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~21.10.1
2021-11-12 15:41:23 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20211014
2021-11-12 15:41:23 INFO      integration_testing:clouds.py:186 image serial: 20211014
-------------------------------- live log call ---------------------------------
2021-11-12 15:41:23 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ip --brief addr'
2021-11-12 15:41:23 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:41:24 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'test -f /etc/udev/rules.d/10-cloud-init-hook-hotplug.rules'
2021-11-12 15:41:34 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-11-12 15:41:35 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ip --brief addr'
2021-11-12 15:41:35 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init devel hotplug-hook -s net query'
PASSEDDeleting snapshot image created for this testrun: 1da51f15-d80a-4493-ae9b-8eb612b94391

------------------------------ live log teardown -------------------------------
2021-11-12 15:41:42 INFO      integration_testing:clouds.py:207 Deleting snapshot image created for this testrun: 1da51f15-d80a-4493-ae9b-8eb612b94391


=============================== warnings summary ===============================
../envs/cloud-init36/lib/python3.6/site-packages/_pytest/config/__init__.py:1184
  /home/james/envs/cloud-init36/lib/python3.6/site-packages/_pytest/config/__init__.py:1184: PytestDeprecationWarning: The --strict option is deprecated, use --strict-markers instead.
    _pytest.deprecated.STRICT_OPTION, stacklevel=2

conftest.py:68
  /home/james/cloud-init-tests/conftest.py:68: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(autouse=True)

conftest.py:168
  /home/james/cloud-init-tests/conftest.py:168: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture

tests/integration_tests/conftest.py:104
  /home/james/cloud-init-tests/tests/integration_tests/conftest.py:104: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='session')

tests/integration_tests/conftest.py:270
  /home/james/cloud-init-tests/tests/integration_tests/conftest.py:270: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture

tests/integration_tests/conftest.py:277
  /home/james/cloud-init-tests/tests/integration_tests/conftest.py:277: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='module')

tests/integration_tests/conftest.py:284
  /home/james/cloud-init-tests/tests/integration_tests/conftest.py:284: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='class')

tests/integration_tests/modules/test_hotplug.py: 502 warnings
  /home/james/envs/cloud-init36/lib/python3.6/site-packages/openstack/resource.py:351: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
    len(inspect.getargspec(type_).args) > 1)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================= 2 passed, 509 warnings in 380.93s (0:06:20) ==================
