=================================================================================================================================== test session starts ====================================================================================================================================
platform linux -- Python 3.5.10, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, configfile: tox.ini
plugins: cov-2.11.1
collected 1 item

tests/integration_tests/modules/test_jinja_templating.py::test_runcmd_with_variable_substitution Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------------------------------------------- live log setup --------------------------------------------------------------------------------------------------------------------------------------
2021-09-23 13:46:53 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
Detected image: image_id=bionic os=ubuntu release=bionic
2021-09-23 13:46:55 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=bionic
PLATFORM=oci
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-09-23 13:46:56 INFO      integration_testing:clouds.py:129 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=bionic
PLATFORM=oci
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for oci
2021-09-23 13:46:56 INFO      integration_testing:conftest.py:156 Setting up environment for oci
Launching instance with launch_kwargs:
user_data=None
image_id=ocid1.image.oc1.phx.aaaaaaaavaly2nuycxgpgffwfakvqf3djoi4h2xul4hmqxivdetzvejttl3q
2021-09-23 13:46:56 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
user_data=None
image_id=ocid1.image.oc1.phx.aaaaaaaavaly2nuycxgpgffwfakvqf3djoi4h2xul4hmqxivdetzvejttl3q
2021-09-23 13:47:28 INFO      pycloudlib.instance:instance.py:176 executing: sh -c whoami
2021-09-23 13:48:01 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-09-23 13:48:01 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-23 13:48:03 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'which systemctl'
2021-09-23 13:48:04 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'systemctl is-active cloud-init.target'
2021-09-23 13:48:05 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'systemctl is-active cloud-init.target'
2021-09-23 13:48:06 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'systemctl is-active cloud-init.target'
2021-09-23 13:48:07 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'systemctl is-active cloud-init.target'
2021-09-23 13:48:08 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'systemctl is-active cloud-init.target'
2021-09-23 13:48:10 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'systemctl is-active cloud-init.target'
2021-09-23 13:48:11 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'systemctl is-active cloud-init.target'
2021-09-23 13:48:12 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'systemctl is-active cloud-init.target'
2021-09-23 13:48:13 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'systemctl is-active cloud-init.target'
2021-09-23 13:48:14 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'systemctl is-active cloud-init.target'
2021-09-23 13:48:15 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'systemctl is-active cloud-init.target'
2021-09-23 13:48:16 INFO      pycloudlib.instance:instance.py:176 executing: cloud-init status --wait --long
2021-09-23 13:48:17 INFO      pycloudlib.instance:instance.py:176 executing: sh -c sync
Launched instance: OciInstance(instance_id=ocid1.instance.oc1.phx.anyhqljrniwq6syc6gfb3ulfg5pqgjgusdgzp63aekcmn7zzmjwnx7pbipea, compartment_id=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa)
2021-09-23 13:48:18 INFO      integration_testing:clouds.py:173 Launched instance: OciInstance(instance_id=ocid1.instance.oc1.phx.anyhqljrniwq6syc6gfb3ulfg5pqgjgusdgzp63aekcmn7zzmjwnx7pbipea, compartment_id=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa)
2021-09-23 13:48:18 INFO      pycloudlib.instance:instance.py:176 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.2-3-g899bfaa9-0ubuntu2~18.04.1
2021-09-23 13:48:18 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.2-3-g899bfaa9-0ubuntu2~18.04.1
2021-09-23 13:48:18 INFO      pycloudlib.instance:instance.py:176 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210825
2021-09-23 13:48:19 INFO      integration_testing:clouds.py:183 image serial: 20210825
Installing proposed image
2021-09-23 13:48:19 INFO      integration_testing:instances.py:152 Installing proposed image
2021-09-23 13:48:19 INFO      pycloudlib.instance:instance.py:176 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-09-23 13:48:19 INFO      pycloudlib.instance:instance.py:176 executing: sudo -- sh -c 'apt-get update -q'
Installing proposed image
2021-09-23 13:48:21 INFO      integration_testing:instances.py:152 Installing proposed image
2021-09-23 13:48:21 INFO      pycloudlib.instance:instance.py:176 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-09-23 13:48:21 INFO      pycloudlib.instance:instance.py:176 executing: sudo -- sh -c 'apt-get update -q'
Installing proposed image
2021-09-23 13:48:25 INFO      integration_testing:instances.py:152 Installing proposed image
2021-09-23 13:48:25 INFO      pycloudlib.instance:instance.py:176 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-09-23 13:48:26 INFO      pycloudlib.instance:instance.py:176 executing: sudo -- sh -c 'apt-get update -q'
2021-09-23 13:48:31 INFO      pycloudlib.instance:instance.py:176 executing: sudo -- sh -c 'apt-get install -qy cloud-init'
Installing proposed image
2021-09-23 13:48:32 INFO      integration_testing:instances.py:152 Installing proposed image
2021-09-23 13:48:32 INFO      pycloudlib.instance:instance.py:176 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-09-23 13:48:32 INFO      pycloudlib.instance:instance.py:176 executing: sudo -- sh -c 'apt-get update -q'
2021-09-23 13:48:40 INFO      pycloudlib.instance:instance.py:176 executing: sudo -- sh -c 'apt-get install -qy cloud-init'
2021-09-23 13:48:47 INFO      pycloudlib.instance:instance.py:176 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.3-1-g6803368d-0ubuntu1~18.04.3
2021-09-23 13:48:48 INFO      integration_testing:instances.py:139 Installed cloud-init version: 21.3-1-g6803368d-0ubuntu1~18.04.3
2021-09-23 13:48:48 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'sudo cloud-init clean --logs'
2021-09-23 13:48:48 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-09-23 13:48:49 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'sudo cloud-init clean --logs'
2021-09-23 13:48:49 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'sudo rm -rf /var/log/syslog'
Created new image: ocid1.image.oc1.phx.aaaaaaaa6u2juajhiej6lsxu5caz6tvhuzltatsyugdzkrfrdtslqnm7tbca
2021-09-23 13:50:56 INFO      integration_testing:instances.py:116 Created new image: ocid1.image.oc1.phx.aaaaaaaa6u2juajhiej6lsxu5caz6tvhuzltatsyugdzkrfrdtslqnm7tbca
Done with environment setup
2021-09-23 13:52:37 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
user_data=## template: jinja
#cloud-config
runcmd:
  - echo {{v1.local_hostname}} > /var/tmp/runcmd_output
  - echo {{merged_cfg._doc}} >> /var/tmp/runcmd_output

image_id=ocid1.image.oc1.phx.aaaaaaaa6u2juajhiej6lsxu5caz6tvhuzltatsyugdzkrfrdtslqnm7tbca
2021-09-23 13:52:37 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
user_data=## template: jinja
#cloud-config
runcmd:
  - echo {{v1.local_hostname}} > /var/tmp/runcmd_output
  - echo {{merged_cfg._doc}} >> /var/tmp/runcmd_output

image_id=ocid1.image.oc1.phx.aaaaaaaa6u2juajhiej6lsxu5caz6tvhuzltatsyugdzkrfrdtslqnm7tbca
2021-09-23 13:53:12 INFO      pycloudlib.instance:instance.py:176 executing: sh -c whoami
2021-09-23 13:53:29 INFO      pycloudlib.instance:instance.py:176 executing: sh -c whoami
2021-09-23 13:53:30 INFO      pycloudlib.instance:instance.py:176 executing: sh -c whoami
2021-09-23 13:53:31 INFO      pycloudlib.instance:instance.py:176 executing: sh -c whoami
2021-09-23 13:53:32 INFO      pycloudlib.instance:instance.py:176 executing: sh -c whoami
2021-09-23 13:53:34 INFO      pycloudlib.instance:instance.py:176 executing: sh -c whoami
2021-09-23 13:53:35 INFO      pycloudlib.instance:instance.py:176 executing: sh -c whoami
2021-09-23 13:53:35 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-09-23 13:53:35 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-23 13:53:38 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'which systemctl'
2021-09-23 13:53:38 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'systemctl is-active cloud-init.target'
2021-09-23 13:53:39 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'systemctl is-active cloud-init.target'
2021-09-23 13:53:41 INFO      pycloudlib.instance:instance.py:176 executing: sh -c 'systemctl is-active cloud-init.target'
2021-09-23 13:53:41 INFO      pycloudlib.instance:instance.py:176 executing: cloud-init status --wait --long
2021-09-23 13:53:42 INFO      pycloudlib.instance:instance.py:176 executing: sh -c sync
Launched instance: OciInstance(instance_id=ocid1.instance.oc1.phx.anyhqljrniwq6sycwgqiojiprsz3dyqkhx6zimlmyy35hmjikaxvdohiyxia, compartment_id=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa)
2021-09-23 13:53:42 INFO      integration_testing:clouds.py:173 Launched instance: OciInstance(instance_id=ocid1.instance.oc1.phx.anyhqljrniwq6sycwgqiojiprsz3dyqkhx6zimlmyy35hmjikaxvdohiyxia, compartment_id=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa)
2021-09-23 13:53:42 INFO      pycloudlib.instance:instance.py:176 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~18.04.3
2021-09-23 13:53:43 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~18.04.3
2021-09-23 13:53:43 INFO      pycloudlib.instance:instance.py:176 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210825
2021-09-23 13:53:43 INFO      integration_testing:clouds.py:183 image serial: 20210825
-------------------------------------------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------------------------------------------
2021-09-23 13:53:43 INFO      pycloudlib.instance:instance.py:176 executing: sudo -- sh -c hostname
2021-09-23 13:53:43 INFO      pycloudlib.instance:instance.py:176 executing: sudo -- sh -c 'cat /var/tmp/runcmd_output'
PASSEDDeleting snapshot image created for this testrun: ocid1.image.oc1.phx.aaaaaaaa6u2juajhiej6lsxu5caz6tvhuzltatsyugdzkrfrdtslqnm7tbca

------------------------------------------------------------------------------------------------------------------------------------ live log teardown -------------------------------------------------------------------------------------------------------------------------------------
2021-09-23 13:55:19 INFO      integration_testing:clouds.py:204 Deleting snapshot image created for this testrun: ocid1.image.oc1.phx.aaaaaaaa6u2juajhiej6lsxu5caz6tvhuzltatsyugdzkrfrdtslqnm7tbca


===================================================================================================================================== warnings summary =====================================================================================================================================
../envs/cloud-init/lib/python3.5/site-packages/jwt/utils.py:8
  /home/james/envs/cloud-init/lib/python3.5/site-packages/jwt/utils.py:8: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
    from cryptography.hazmat.primitives.asymmetric.utils import (

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================================================================= 1 passed, 1 warning in 506.95s (0:08:26) =========================================================================================================================
