=================================================================================================================================== test session starts ====================================================================================================================================
platform linux -- Python 3.5.10, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/james/cloud-init-tests, configfile: tox.ini
plugins: cov-2.11.1
collected 1 item

tests/integration_tests/modules/test_user_events.py::test_boot_event_enabled Detected image: image_id=bionic os=ubuntu release=bionic

-------------------------------------------------------------------------------------------------------------------------------------- live log setup --------------------------------------------------------------------------------------------------------------------------------------
2021-09-09 13:23:09 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
Detected image: image_id=bionic os=ubuntu release=bionic
2021-09-09 13:23:09 INFO      integration_testing:clouds.py:88 Detected image: image_id=bionic os=ubuntu release=bionic
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=bionic
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-09-09 13:23:09 INFO      integration_testing:clouds.py:129 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=bionic
PLATFORM=azure
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
Setting up environment for azure
2021-09-09 13:23:09 INFO      integration_testing:conftest.py:156 Setting up environment for azure
Launching instance with launch_kwargs:
image_id=Canonical:UbuntuServer:18.04-DAILY-LTS
user_data=None
2021-09-09 13:23:09 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
image_id=Canonical:UbuntuServer:18.04-DAILY-LTS
user_data=None
2021-09-09 13:25:13 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-09 13:25:13 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-09-09 13:25:14 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-09 13:25:15 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fa6b66347b8>
2021-09-09 13:25:16 INFO      integration_testing:clouds.py:173 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fa6b66347b8>
2021-09-09 13:25:16 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.2-3-g899bfaa9-0ubuntu2~18.04.1
2021-09-09 13:25:17 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.2-3-g899bfaa9-0ubuntu2~18.04.1
2021-09-09 13:25:17 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210908
2021-09-09 13:25:17 INFO      integration_testing:clouds.py:183 image serial: 20210908
Installing proposed image
2021-09-09 13:25:17 INFO      integration_testing:instances.py:150 Installing proposed image
2021-09-09 13:25:17 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-09-09 13:25:18 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
2021-09-09 13:25:29 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get install -qy cloud-init'
2021-09-09 13:25:41 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init -v'
Installed cloud-init version: 21.3-1-g6803368d-0ubuntu1~18.04.2
2021-09-09 13:25:42 INFO      integration_testing:instances.py:137 Installed cloud-init version: 21.3-1-g6803368d-0ubuntu1~18.04.2
2021-09-09 13:25:42 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-09-09 13:25:42 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-09-09 13:25:42 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-09-09 13:25:43 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-09-09 13:25:43 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo waagent -deprovision+user -force'
Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0909-082309-rg/providers/Microsoft.Compute/images/azure-integration-test-0909-082309-image
2021-09-09 13:26:45 INFO      integration_testing:instances.py:114 Created new image: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0909-082309-rg/providers/Microsoft.Compute/images/azure-integration-test-0909-082309-image
Done with environment setup
2021-09-09 13:27:26 INFO      integration_testing:conftest.py:162 Done with environment setup
Launching instance with launch_kwargs:
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0909-082309-rg/providers/Microsoft.Compute/images/azure-integration-test-0909-082309-image
user_data=#cloud-config
updates:
  network:
    when: [boot]

2021-09-09 13:27:26 INFO      integration_testing:clouds.py:168 Launching instance with launch_kwargs:
image_id=/subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0909-082309-rg/providers/Microsoft.Compute/images/azure-integration-test-0909-082309-image
user_data=#cloud-config
updates:
  network:
    when: [boot]

2021-09-09 13:28:13 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-09 13:28:13 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-09-09 13:28:13 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-09 13:28:14 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fa6b5ccecf8>
2021-09-09 13:28:15 INFO      integration_testing:clouds.py:173 Launched instance: <pycloudlib.azure.instance.AzureInstance object at 0x7fa6b5ccecf8>
2021-09-09 13:28:15 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~18.04.2
2021-09-09 13:28:16 INFO      integration_testing:clouds.py:179 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~18.04.2
2021-09-09 13:28:16 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
image serial: 20210908
2021-09-09 13:28:16 INFO      integration_testing:clouds.py:183 image serial: 20210908
-------------------------------------------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------------------------------------------
2021-09-09 13:28:16 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-09-09 13:28:16 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ls /sys/class/net'
2021-09-09 13:28:16 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/netplan/50-cloud-init.yaml'
2021-09-09 13:28:16 INFO      paramiko.transport.sftp:sftp.py:158 [chan 7] Opened sftp connection (server version 3)
2021-09-09 13:28:16 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'mv /var/tmp/b0502b37-20e4-44e4-825e-f456dc8d55db.tmp /etc/netplan/50-cloud-init.yaml'
2021-09-09 13:28:16 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'rm /var/log/cloud-init.log'
Restarting instance and waiting for boot
2021-09-09 13:28:16 INFO      integration_testing:instances.py:66 Restarting instance and waiting for boot
2021-09-09 13:28:47 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-09-09 13:29:03 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-09-09 13:29:03 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-09-09 13:29:05 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
2021-09-09 13:29:06 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2021-09-09 13:29:06 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'ls /sys/class/net'
PASSEDDeleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0909-082309-rg/providers/Microsoft.Compute/images/azure-integration-test-0909-082309-image

------------------------------------------------------------------------------------------------------------------------------------ live log teardown -------------------------------------------------------------------------------------------------------------------------------------
2021-09-09 13:29:46 INFO      integration_testing:clouds.py:204 Deleting snapshot image created for this testrun: /subscriptions/36c65514-b88a-44f1-a44a-795c5b6fb73c/resourceGroups/azure-integration-test-0909-082309-rg/providers/Microsoft.Compute/images/azure-integration-test-0909-082309-image
------------------------------------------------------------------------------------------------------------------------------------ live log logreport ------------------------------------------------------------------------------------------------------------------------------------
2021-09-09 13:29:47 INFO      paramiko.transport.sftp:sftp.py:158 [chan 7] sftp session closed.


===================================================================================================================================== warnings summary =====================================================================================================================================
../envs/cloud-init/lib/python3.5/site-packages/jwt/utils.py:8
  /home/james/envs/cloud-init/lib/python3.5/site-packages/jwt/utils.py:8: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
    from cryptography.hazmat.primitives.asymmetric.utils import (

tests/integration_tests/modules/test_user_events.py: 45 warnings
  /home/james/envs/cloud-init/lib/python3.5/site-packages/urllib3/util/retry.py:440: DeprecationWarning: Using 'method_whitelist' with Retry is deprecated and will be removed in v2.0. Use 'allowed_methods' instead
    DeprecationWarning,

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================================================================================================================== 1 passed, 46 warnings in 398.51s (0:06:38) ========================================================================================================================
